### ISSUE TITLE
Usage on 16.04.2 LTS (Xenial Xerus)

### ISSUE THREAD

**Issue by lilloxxx** [SmeegeSec/SmeegeScrape#4]
Hi,
I'm not very familiar with python and I'm encountering some difficulties to run the script.

Please is it possible to know if the script correctly run in Ubuntu 16.04.2 LTS.

I report what i did:

`wget https://raw.githubusercontent.com/SmeegeSec/SmeegeScrape/master/SmeegeScrape.py`
`python SmeegeScrape.py`
`pip install docx`
`pip install python-pptx`

```
 python SmeegeScrape.py
Traceback (most recent call last):
  File "SmeegeScrape.py", line 27, in <module>
    import nltk #http://pypi.python.org/pypi/nltk, pip install -Iv nltk==2.0.4
ImportError: No module named nltk
notroot@ubuntu:~$ python SmeegeScrape.py
Traceback (most recent call last):
  File "SmeegeScrape.py", line 27, in <module>
    import nltk #http://pypi.python.org/pypi/nltk, pip install -Iv nltk==2.0.4
ImportError: No module named nltk
```

I can not install  nltk==2.0.4, I receive many errors during the installation of the module.

Thanks for any info.

Regards,
lilloxxx

**Comment by maaaaz** [comment]
Hello there,

Use that command to install everything, including a working pre-compiled version of `nltk`:
```
pip install docx python-pptx PyPDF2 https://s3-us-west-2.amazonaws.com/jdimatteo-personal-public-readaccess/nltk-2.0.5-https-distribute.tar.gz
```

Source: https://stackoverflow.com/questions/46977498/urllib2-httperror-http-error-403-ssl-is-required-when-installing-nltk-2-0-5
